### ISSUE TITLE
Keys doesn't refresh

### ISSUE THREAD

**Issue by sokeroner** [echodot-llc/Red#14]
Sometimes the list of keys doesn't refresh when I click on "Reload keys now".
I have to close red or switch the database and then come back to make it working again.

https://user-images.githubusercontent.com/923990/135303965-e9da53cb-d5db-4523-ade0-54fa2871a4a3.mov

**Comment by scuml** [comment]
Great report.  Love the video.  Looks like a cache issue - I'll check into it.  In the meantime - there's a secret "Hard Reload" feature if you press 'Command-Option-Shift-R' which will likely work.

**Comment by scuml** [comment]
Fixed in version 2.0.

https://echodot.com/red/download/

**Comment by sokeroner** [comment]
Hi, I'm currently using the version 2.1.3 (build 7489) on macOS and it seems to me that the problem still occurs sometimes.

**Comment by scuml** [comment]
Are the missing keys in the main list, or in subdirectories?  Does "Command-Option-Shift-R" bring them back?

**Comment by sokeroner** [comment]
Hi, I made the test and even the "Command-Option-Shift-R" does not work. I have to change my DB and go back to my DB to make it work (in my case it's in subdirectories)
